### ISSUE TITLE
Why all the protocol complexity?

### ISSUE THREAD

**Issue by mattcollier** [ricochet-im/ricochet#149]
I was inspired by this project and the venerable 'tor chat' to create a tor hidden service oriented instant messaging application myself:  https://github.com/mattcollier/noxious

I implemented a RESTful approach which to me seemed a natural fit for an instant messaging application.  Messages are digitally signed, encrypted, placed into a JSON object and transmitted via an HTTP POST to the recipients tor hidden service address.  Public Key exchange takes place using the 'send invite' paradigm.  Message delivery confirmation is handled simply by HTTP response headers.

I was looking into what it would take to have noxious speak the ricochet protocol and I'm flabbergasted by the amount of complexity built into the protocol.  Is there really a need to reinvent the wheel here?

**Comment by special** [comment]
Yes, the Ricochet protocol is complex. More than I would like it to be, in some places. Some of that would be different with hindsight, but some of it is very intentional.

I'll try to explain some decisions, though, in a Q&A format so I can refer back to this later:

##### Why a custom network protocol instead of something like HTTP?
We use one connection for bidirectional traffic. Most of the common examples, like HTTP, are client/server and can only initiate unidirectionally (client requests, server responds).

I did some surveying, but I wasn't able to find anything more compelling that was fully bidirectional without adding unnecessary or risky complexity. Are there any particular options I missed?

##### Why protobuf instead of JSON?
Protobuf defines a message syntax and generates parsers for it. JSON is a free-form serialization format. Using protobuf puts the majority of the message handling into safer, generated code. It's a stricter definition of the contents of a message.

##### Shouldn't it be a goal to be as simple and easy to reproduce as possible?
This is a controversial point of view: I don't think having many casual implementations of Ricochet's protocol would be a good thing. The security requirements here are higher than usual, and doing that properly requires care and careful thought. I'd be thrilled to see other tools compatible with Ricochet, but only if they're also compatible with the standard of quality we're trying to create - not just code quality, but also UX, user trust, etc. So, speedy implementation isn't a priority.

##### How complicated is it, really?
I bet the current protocol documentation is a lot harder to understand than the protocol itself. I'm not very good at writing those things. Maybe it's not as bad as you think. Is there anything in particular that you're confused about?

-----

I think a key difference, when comparing Ricochet to something like TorChat, is the scope of the project. TorChat was a prototype, a tech demo. Ricochet is trying to be a product - not in the commercial sense of the word, but in regards to robustness, polish, experience, and behavior. If it leads to a better result, I'd rather things be done the hard and slow way, even if it would be possible to build more functionality faster.

If you're interested in discussing it and building another client, I'm happy to help explain and to work with you on making things simpler where possible. Even better would be if you're interested in helping to improve on Ricochet and point out where our bad decisions are.

**Comment by hkparker** [comment]
Thanks for putting this together @special, clears some things up.  I've been very interested in ricochet since I had a similar idea, went on the TOR IRC, and was directed here :).  HTTP requests came to mind in my designs as well, as the client can multiplex multiple HTTP requests through one TCP socket when they are made in quick succession, and not have to maintain an open connection all the time if not, so that seemed advantageous when access is unreliable.  Channels are very extensible however and make it easy to add new services, where HTTP might create some challenges when implementing more complicated services.  I didn't find the documentation too bad.

I think your point on making a "product" in the sense that everything is well polished is crucial for adoption, so I'm glad to see thats a priority.  I want to see an easy to use chat application that is cross platform and prevents metadata collection, and I want to do what I can to make that happen.  Ricochet has a solid code base, so it makes sense to contribute, but it might be worth forking the concept and creating an HTTP based client to test the idea.  I would try to bring in some other concepts as well, such as multi-device syncing (see #99), and try to make the library as mobile-friendly as possible.  We should get in touch some time soon.

**Comment by special** [comment]
> HTTP requests came to mind in my designs as well, as the client can multiplex multiple HTTP requests through one TCP socket when they are made in quick succession, and not have to maintain an open connection all the time if not

I think the unidirectional issue is still an important one; you lose a _lot_ in reliability if you require two connections to maintain a chat.

Ricochet maintains a constant open connection with its contacts so that it can tell when they're online - it's less resource intensive for the Tor network than constant polling. There might be some smarter things to do here someday, though.

> Ricochet has a solid code base, so it makes sense to contribute, but it might be worth forking the concept and creating an HTTP based client to test the idea. I would try to bring in some other concepts as well, such as multi-device syncing (see #99), and try to make the library as mobile-friendly as possible.

@hkparker I'm interested to discuss what you have in mind - especially for the synchronization and mobile challenges. Please do stay in touch! My personal contact info is in the readme, and I'm around tor IRC as _special_.

For the moment, this bugtracker is the best place to discuss and record ideas in public. Absolutely feel free to use it for that. Maybe soon we'll have enough active contributors for a mailing list to make sense too :)
