### ISSUE TITLE
Logging to file

### ISSUE THREAD

**Issue by bigfighter** [ricochet-im/ricochet#168]
It would be nice if there was an option to log conversations to file.
The file should be in plain text format, to facilitate plausible deniability.

My suggestion: `ricochet/log/2015/04/13/rs7ce36jsj24ogfw.log`
That way different contacts don't show up in the same log file, and log files don't grow out of bounds.

For the file content, I suggest this:

    08:50:03 > Hi there!
    08:50:27 < How's it going?

First the time in HH:MM:SS format, then ">" (to indicate that I said something to my contact) or "<" (to indicate that my contact said something to me), then the actual message.

Both date (file path) and time (file content) should be in UTC, to avoid duplicates when daylight saving ends.

Newline characters in the message need to be escaped.

**Comment by special** [comment]
I have two non-technical concerns that I'd like to discuss:

##### Having a logging capability makes it easier for users to hurt themselves
Many people will consider turning logging on, because logging is useful. I'm worried those people might not understand that it means their messages are now forever readable on disk, and might not understand how hard it is to securely delete those records.

>  The file should be in plain text format, to facilitate plausible deniability.

This is a great example. Most civil and criminal courts consider these kind of log files as admissible evidence. It doesn't matter that they could have plausibly been modified. Often, plausible deniability doesn't matter just because of the content of messages.

We could try to handle this with a warning about records and data security. I'm not sure if that would be helpful.

##### Having a logging capability makes it easier for users to hurt their contacts
Whether acting maliciously or not, your contacts' logging also exposes you to risks. It's pretty rude to record conversations that people expect to be ephemeral, and having that capability might reduce people's confidence in the ephemerality of their words.

Of course, nothing can _prevent_ your contacts from doing this, even if we didn't include the feature. Maybe it's better that users know it is possible, so they can act accordingly and judge their contacts on character.

We could try to help this with software, by having a client tell its contacts that conversations are being logged. That is somewhat of a false confidence, because it could be disabled locally.

Another attempt at a middle ground would be allowing a conversation to be saved after the fact, but not have an automatic "log everything" option.

----

So with the understanding that a determined person _can_ keep logs, I think the questions are:

1. Do the benefits outweigh the risks to users and justify making it easy to keep logs?
2. If so, how should we do it to best balance those in favor of users' safety?

Thoughts?

**Comment by bigfighter** [comment]
My personal view on this is simple, but it obviously doesn't apply to everyone:

 * Logging is useful to me.
 * Logging is possible, because I'm a programmer.
 * If you're going to chat with me, I'm going to log it.

The best that Ricochet can do for my contacts is to not give them a false sense of security.

One way to do that would be a warning message in the settings dialog, similar to how Chrome tells you what incognito mode can and cannot do.

**Comment by special** [comment]
Yeah, I understand. Warning the user about this should be part of a broader, accessible explanation on what is and isn't private and from whom.

I don't think it's appropriate for Ricochet to include this feature. I don't oppose _all_ ability to persist messages, but I don't think doing it this way is useful or safe to most of Ricochet's users. There are some variations (brief conversation history, rotated with erasure keys?) that might be interesting. Anyone who has strong feelings about this, please share them.

Personally, I encourage people to take notes in their own words instead of keeping verbatim records.

**Comment by Mromson** [comment]
Record-keeping is an important aspect of keeping track of conversations and people will aim to do so wherever possible. The moment you choose to open a conversation with someone, there's literally nothing they can do to prevent it from being logged - the best we can do, is try to attach some control to it. I think logging should be disabled by default, but allowed to be enabled with sufficient warning - furthermore, the client should have the capability of "requesting" that the conversation is to not be logged, which would be by default complied with, but with the recipient being able to ignore it at his/her discretion (again, with the proper warning attached on both ends).

I would argue that there's a limit to how much you can (and should) protect users from others and themselves - attaching a sufficiently (red) warnings to potentially harmful actions should be sufficient to protect users. At least this way, you reduce the potential risk of users going outside of the apps ecosystem to do the things you wish to protect users from.

Being able to use the client for daily day-to-day usage needs to be accommodated for, assuming _any_ measure of widespread adaptability is desired.

**Comment by modrobert** [comment]
I use encrypted file system containers to store all communication programs/logs, both for increased security and portability when moving between computers or other operating system. In my case it makes a lot of sense having a setting to enable clear text logs of the chat per user (similar to torchat), something to 'grep' on when memory fails about agreements and similar details.

**Comment by boite** [comment]
It would be really nice if ricochet conversations could be relied upon to be ephemeral; it cannot, as has been stated previously in this thread.

There is then a possible benefit to adding logging as a feature (accompanied by suitable threat info): the logging client can signal to the correspondent’s client that it is recording the conversation, thereby giving the correspondent the opportunity to take care with what they say.

@Mromson mentioned the ability for a client to request that a conversation be not logged.  This is a really good idea. It could be used to turn-off logging at both ends of the conversation if the request is accepted and it would signal the requester to take care if the request is denied.

**Comment by special** [comment]
@boite @Mromson I could imagine the following:

* A preference for "allow contacts to keep conversation history", with the options "always", "never", and "ask" (default)
* A preference for "keep conversation history", with the options "for [n] days", "last [n] messages", or "no"
* At the start of a conversation, display the logging status (for both sides) in the chat window
* In "ask" mode, when the contact signals that they'd like to keep history, offer a simple yes/no option inline. Assume no until explicitly approved. The choice is saved as the default for that contact.

This is complicated, but it seems like a reasonable usability tradeoff, and a good way to indicate expectations about the ephemerality of conversations to the user. Of course, we can't guarantee that the contact isn't logging anyway, but that's also true right now..

I would also require that these logs are encrypted and forward-secure on disk.

**Comment by gaditb** [comment]
A possible simplification (but also possibly not) over "keep conversation history":
"Stop Chatting" and "End Conversation" (Possible "Stop Chatting For Now"?)

"Stop Chatting" closes the window but saves the logs for next time.
"End Conversation" closes the window and wipes the logs.

That way, there is a specific semantically meaningful breakup of when logs are kept vs. deleted, and within a given conversation, if you want to refer back to something, it's there.

Potential downside: people might just keep clicking "Stop Chatting"?
This could maybe be avoided with a "Delete Unactive Conversations After <time>" option.
But that wouldn't help if someone chatted with one person regularly over a long period of time...
(maybe a notification? "You have over one month of logs in this conversation -- would you like to truncate the logs?" But then allowing time and "always truncate" would be another two settings...)


Separately, if we begin keeping logs, I'd like to suggest implementing a self-destruct request as requested in issue #335?
While yes, self-destruct is not cryptographically meaningful, perhaps if it were phrased as "Request Self-Destruct" it would be unambiguous that there were no guarantees?
(And then the main client would just not have any options to ignore that.)
Because then it is a meaningful request, at least, just like asking for no logging.
(Perhaps this could be extended into a general "Request Deletion" on previously sent messages, too?)
/thoughtdump

**Comment by burdges** [comment]
There is no way to enforce a "never store my conversations" options.  I know enough folks who'd use that even when doing something that needs storage, like sending you their temporary phone number, that a "setting" sounds more annoying that useful.

I'd suggest that all conversations be deleted by default, but messages have a "retain & edit" contextual menu item, or maybe a checkbox next to them ala Pond, thereby allowing you to retain just the few message where that need retention.  

It would not be a dumb log though because it also makes the message text conveniently editable, so that (a) you can optimize the content of the message you retain, like if they give you someone else's number, and (b) the retained message have minimal value as evidence. 

Also, if you unclick "retain & edit" the message should go back to being a normal message, albeit possibly modified, thereby devaluing even ricochet screen shots as evidence.  And you should be able to "retain & edit" your own sent messages too.

It'd be good to analyze the protocol to make sure it cannot provide corroboration of recorded messages, primarily by making sure no signatures get use, or if essential get kept even ephemerally, but maybe by stuff like adding padding.
