### ISSUE TITLE
Bypass context menu when link is left-clicked and no-promt is set

### ISSUE THREAD

**Issue by sergeevabc** [ricochet-im/ricochet#181]
Current Ricochec 1.1.0 behaviour when some chat link is left-clicked is to promt user with actions either to copy link or open it with browser. It's expected to open link directly with no additonal choices when no-promt checkbox (in Preferences-General) is set.

![](https://i.imgur.com/3pFJMv6.png)

**Comment by gabedwrds** [comment]
I see three options (this is all in the context of left-click):

1. Status quo: Always open context menu
2. Bypass context menu when no-prompt is set
3. Bypass context menu entirely and rely on the "Warning!" dialog to prevent accidentally opening sensitive links in my main browser

![screen shot 2015-04-26 at 20 31 06](https://cloud.githubusercontent.com/assets/1580619/7340080/31a2d67a-ec53-11e4-9729-9954a03c2825.png)

2 and 3 would both open links immediately with just a left-click, if the user has decided not to be asked again.

I think option 2 is a little wishy-washy for me. Opening a context menu with a left-click is kind of unusual and it should at least be consistent about it. I'd prefer one extreme or the other.

I like the simplicity of option 3 - it's what most people might expect - but it complicates the scenario where *most* links are fine to open in my main browser. I enable no-prompt because I understand the risks, but I still want that extra gate (the context menu) to go through to prevent accidentally opening something unwanted in my main browser. I could turn no-prompt back off, but that warning dialog is significantly more annoying to go through (as it should be).

This is entirely a design decision. IMO, as long as this is privacy-oriented software, it's good to confirm the user's intent before exposing them to risk. I'm in favour of the status quo because it accomplishes that goal with minimal inconvenience.

**Comment by special** [comment]
For now, we'll stick with the current design and always show the context menu.
