### ISSUE TITLE
Scripting of Ricochet protocol

### ISSUE THREAD

**Issue by JeremyRand** [ricochet-im/ricochet#206]
It would be nice to have scripting language bindings (e.g. Python) for the Ricochet protocol, for people who want to use the protocol but don't want to use C++.

**Comment by s-rah** [comment]
This is actually something that crossed my mind - I've been thinking of various testing tools - a few random thoughts:

1. This would probably be much easy if the core protocol internals of Ricochet were broken out into a separate library first i.e. libricochet
2.  The exact level of granularity in the exposed API needs to be nicely restricted to prevent leaking of metadata etc.
2b. Because so many of the potentially scriptable actions update a config file - the exact mechanics of this file need to be thought about - in particular if people script addons that affect an existing profile then how to not screw that profile when multiple programs want to write to it. (The main Ricochet code currently locks the config file at start up)

A couple of straw-apis:

<code>
init(optional string path/to/tor) return string ricochetAddress
requestContact(string ricochetAddress, string niceName, string message)
renameContact(string oldNiceName, string newNiceName)
removeContact(string niceName)
sendMessage(string niceName, sting message)
</code>

**Comment by special** [comment]
Cool old bug -- @s-rah's thoughts there turned into https://github.com/s-rah/go-ricochet, which is what I'd point you to today.

More implementations always welcome, but there are no plans to do anything first-party other than C++ and Go.
