### ISSUE TITLE
Feature request: support tab-view for chat windows

### ISSUE THREAD

**Issue by mrphs** [ricochet-im/ricochet#213]
when you've multiple chat windows open, they all appear on the same exact location and you can never find out how many are open and which one is on top of which. 

one way to solve this issue to have them appear in random locations, instead of over each other. 

the other way (probably the better one) is to support tabs for chat windows. 

a way better one, is to have both options and give users the ability to chose which one suits them best.

**Comment by special** [comment]
I think the single window mode effectively is a tabbed window. A difference is that it shows all of your online people instead of just the ones you're actively talking to, but this is a detail, and I can imagine some change or setting where the active conversations end up at the top. I also like that UI better than literal tabs - I think it makes a lot more sense in IM.

The windows opening on top of eachother does indeed sound bad. They should be better at spreading out, if they're going to keep opening that way.

**Comment by special** [comment]
Closing this on the basis of:

1. There haven't been any compelling UX reasons proposed for using tabs, as opposed to the combined window view
2. Multi-window is not the default anymore, will likely be going away entirely, and issues that remain with how those windows are opened should be separate bugs.
