### ISSUE TITLE
Option to store config files in directory other than app dir

### ISSUE THREAD

**Issue by schnauss** [ricochet-im/ricochet#220]
Of course, offering the option to keep things "portable" in the same directory. On OSX, it could live under ~/Library, Windows under AppData\Roaming, et cetera.

**Comment by special** [comment]
Here's the logic as it is right now (1.1.0):

1. If `RICOCHET_NO_PORTABLE` is defined during build, use the system-defined user configuration path
2. On OS X, if the path contains `/Applications`, use the system path
3. Otherwise, use the same directory as the application

What should we improve here?

**Comment by schnauss** [comment]
OK, that makes sense. I first ran it outside /Applications and then, realizing my mistake, copied everything to /Applications assuming that Ricochet would expect the config files to be in the same relative directory.
