### ISSUE TITLE
Can I discard one conversation backlog without discarding all of them?

### ISSUE THREAD

**Issue by armadev** [ricochet-im/ricochet#273]
Let's say I have a chat with Alice for a while, and also a chat with Anne at the same time.

Later I want to not have the backlog from Alice on my screen anymore, but I don't want to throw out the backlog with Anne yet.

How can I do this?

**Comment by burdges** [comment]
Do you mean within a session?  I have not looked at the code, but the interface offers no logging functions afaik, so closing the chat window and reopening it seemingly wipes the history.  That's potentially intentional.

If you need to save conversation details for longer, then maybe you should copy them into an editor?  In the long term, one could imagine dealing with this by offering a "retain" contextual menu item, that applied to individual IMs or a collection of selected IMs, similar to pond.  All retained IMs could reappear when a conversation window is reopened, but now with a "retain" checkbox next to them.  In this way, users could be encouraged to retain exactly the IMs they need, like addresses, phone numbers, etc., and leave the vast majority ephemeral.

**Comment by armadev** [comment]
I do mean within a session. I'm using the "use a single window for conversations" option. In that case, there is no way to close the chat window that isn't the same as closing ricochet itself. I think.

**Comment by special** [comment]
This sounds like an easy UI task. Anyone interested? :)

Ideally, it should come with a reasonable hotkey and a button in the empty header above the conversation.

**Comment by burdges** [comment]
In the short term, the easiest option would probably be a "close this conversation" contextual menu item in the "single window for conversations" mode.

**Comment by special** [comment]
Oops, I've built up a set of duplicates on this. We'll keep #507 since it's more direct about the desired UI changes. I'm still hoping someone decides to take this as an easy intro contribution.

Thanks!
