### ISSUE TITLE
Switch to LibreSSL

### ISSUE THREAD

**Issue by taoeffect** [ricochet-im/ricochet#284]
http://www.libressl.org/

It's backwards compatible with OpenSSL and more secure.

Apple has switched to it on El Capitan, so things are (rightly) moving in that direction.

For security critical applications like Ricochet, it's very important to get off of OpenSSL. Thankfully LibreSSL seems to be a drop-in replacement (we're also replacing OpenSSL with it in the next version of our app).

**Comment by pludi** [comment]
Not to slight LibreSSL, but they already had two pretty serious bugs ([CVE-2015-5333 and CVE-2015-5334](https://www.qualys.com/2015/10/15/cve-2015-5333-cve-2015-5334/libressl-cve-2015-5333-cve-2015-5334.txt)), that didn't affect OpenSSL.

**Comment by taoeffect** [comment]
I thought I remembered some bugs that affected OpenSSL and didn't affect LibreSSL, but I cannot find links for that.

Oh well. OpenSSL has been around for a long time, and for its entire history it has let the world down. You know what they say about insanity...

Personally, I much rather both were ditched and something like [ocaml-tls](https://github.com/mirleft/ocaml-tls) used in its place (or a Rust implementation, however I'm not aware of one that's as close to completion as that ocaml one, which seems to be fully functional).

**Comment by DomT4** [comment]
> Apple has switched to it on El Capitan

This isn't entirely accurate, as far as I'm aware at least :question:. They switched to LibreSSL for OpenSSH with what was a private dylib during the first three developer previews and since that point seems to be statically built into the binary. There's merit to using LibreSSL for OpenSSH for obvious reasons, but a bunch of stuff still breaks as evidenced by [Gentoo's dedicated fix repo](https://github.com/gentoo/libressl).

The standard OpenSSL (Sans headers since 10.11) in `/usr` is still the truly terrible 0.9.8 branch, and that's what `php`, `unbound`, `ntpd` and so on are still using (Again, AFAIK).

**Comment by taoeffect** [comment]
Thanks for the accuracy check, @DomT4!

**Comment by special** [comment]
Ricochet itself only uses libcrypto, and just for RSA/SHA operations.

The tor binaries use OpenSSL. I don't buy into the "LibreSSL is more secure" argument at this point - I've seen no factual basis for switching. Tor's binary releases all continue to use OpenSSL.

**Comment by hasufell** [comment]
> I've seen no factual basis for switching.

Switching? The code doesn't even compile with libressl right now, because of openssl version-specific ifdefs. Instead, it should ifdef for feature-macros or define it's own macros which are tested by the build system (e.g. in autotools that would be [AC_COMPILE_IFELSE ](https://www.gnu.org/software/autoconf/manual/autoconf-2.66/html_node/Running-the-Compiler.html)), no idea if/how you do it in qmake.

Then you just need to verify that the resulting libressl codepath is safe and doesn't do something weird.

**Comment by DomT4** [comment]
For what it's worth since my last comment, macOS has pretty much moved over to `libressl` as widely as possible now. The writing was on the wall but they took a while to start moving things, and then moved things over very quickly, at least in Sierra.

As is the case with both `libressl` and `openssl` on macOS neither ship the headers anywhere public though.

**Comment by special** [comment]
> Switching? The code doesn't even compile with libressl right now, because of openssl version-specific ifdefs. Instead, it should ifdef for feature-macros or define it's own macros which are tested by the build system (e.g. in autotools that would be AC_COMPILE_IFELSE ), no idea if/how you do it in qmake.

Thanks for the PR on this. We do need to support LibreSSL, I agree.

> As in: support libressl, don't switch to it.

The "switch" in this bug is referring to the binary releases. I'm going to keep using OpenSSL for those for now, because 1) ricochet itself only needs libcrypto in the simplest way, where there is no meaningful distinction, and 2) tor's upstream binary releases use OpenSSL, and I prefer to match with them for the tor build we distribute, unless there's a compelling reason not to.
