### ISSUE TITLE
Any troopers want to implement a non-C++ version?

### ISSUE THREAD

**Issue by taoeffect** [ricochet-im/ricochet#285]
C/C++ and security do not mix.

These languages are ancient, prone to vulnerabilities, and should be discarded for security-related projects.

Since Ricochet has defined a protocol, it makes it easier for someone to create an implementation in safer languages.

**Comment by taoeffect** [comment]
There is also the option of using a language like [Elm](http://elm-lang.org/) or [TypeScript](http://www.typescriptlang.org/) and creating native desktop apps out of them using [Electron](http://electron.atom.io/) or similar (& something like [Cardova](https://cordova.apache.org/) for mobile).

**Comment by taoeffect** [comment]
Changed title to just be "non-C++". I'll use this comment to list various safer (and interesting) languages Ricochet could be implemented in.

- **Racket.** If you want type checking, has [Typed Racket](http://docs.racket-lang.org/ts-guide/)). Has support for creating desktop GUIs and self-executing binaries.
- **Rust.** Is like a safe version of C++. Clunky syntax and manual memory management still, but compiler and design forces memory and thread safety.
- **TypeScript, Elm, CoffeeScript, ES6... etc.** See [previous comment](https://github.com/ricochet-im/ricochet/issues/285#issuecomment-154223619) for links and details.
- **OCaml.** Safe, performant, smart compiler, fast, and elegant-looking syntax. However, seems to have a steep learning curve and I don't know its desktop GUI story.
- **Go.** Easy to learn, simple syntax, and growing community. Supposedly some folks are developing GUI related libraries for it, but I don't know how mature they are. However, it can call out to C/C++.

**Comment by burdges** [comment]
Meh.  Ricochet should end up relatively isolated behind Tor.  Is it using authenticated hidden services yet?  If not, work on that first.  If so, we're only facing attacks by contacts, so maybe a little quality time with `valgrind` first. 

As for alternative language choices :  
- Python has the best Tor control support via stem.  Why not a simple text mode Ricochet client in Python for the paranoid people? 
- Afaik Rust is the only language you list with an active effort towards a Tor control port library : https://github.com/du5t/puccinia  Rust has efforts to automate the process of building Rust bindings for C++ libraries too.  You could replace only the "dangerous" bits of C++ code by Rust code. 
- Avoid writing non-web GUIs in Go since Go does not play so well with outside libraries. 
- I love Haskell.  Ain't too hard to learn either since the community is fabulous.  It even gets used for CS101 occasionally.  It's fancy research language terminology does however scare off folks who might wish to contribute.

**Comment by shak-mar** [comment]
Me and some friends have started implementing the ricochet protocol in Haskell.  It was our project at JugendHackt Berlin (A hackathon) and we’re still working on it.  You can take a look at it:
https://github.com/Jugendhackt/haskell-ricochet

**Comment by taoeffect** [comment]
@shak-mar That's great news! Very cool stuff! :+1: Posted a [tweet](https://twitter.com/taoeffect/status/663147258150424576). :smile:

**Comment by special** [comment]
It's entirely possible to write secure software in C or C++. Ricochet is also focused on being usable secure software, which is part of the reason for using C++; Qt gives us the ability to write a decent user interface.

There are also some prototype Go implementations by others. Maybe we should collect these on a wiki page somewhere.

https://github.com/yawning/ricochet
https://github.com/s-rah/go-ricochet

**Comment by taoeffect** [comment]
> It's entirely possible to write secure software in C or C++.

No one said it wasn't possible. C and C++, however, make it far more likely that the software will have security related bugs, or just bugs in general.

> Maybe we should collect these on a wiki page somewhere.

I think that's a great idea!

I've started one here: https://github.com/ricochet-im/ricochet/wiki/Third-Party-Implementations-of-the-Ricochet-Protocol

**Comment by whatisgravity** [comment]
Are these just leveraging the control API and not running their own instance of Tor like richochet C++ client does?
