### ISSUE TITLE
Documentation request for Tails setup

### ISSUE THREAD

**Issue by xagifu** [ricochet-im/ricochet#31]
Tails is Debian based and most of its software is configured to be routed through Tor. It is unclear if Torsion would run as expected by default. One concern is that it may direct the traffic through Tor before starting a the hidden service circuit. 
Desired circuit:
user > guard > middle > rend-point < middle < middle < guard < user

Since torsion is packaged with a Tor client it might be configured to send its tor traffic out through a default network, which in Tails could be understood to be Tor, which could result in Tor going through Tor.
Tor within Tor circuit: 
user > guard > middle > exit-node > guard > middle > rend-point < middle < middle < guard < user

For a basic example for TorChat in Tails setup: http://pastebin.ro/PcF3YA3p

**Comment by special** [comment]
To summarize here, the problems are:

1. Ricochet can't publish a hidden service through the system's tor instance
2. Ricochet can't run its own tor instance, because of the restrictions on localhost tcp. Even if it did, that would be tor-through-tor.

Once it's possible to publish hidden services with the tor control socket (https://bugs.torproject.org/6411), it might be possible to work with the tails people to give ricochet the access it would need. That should happen with tor 0.2.7.x.

**Comment by special** [comment]
This is pretty far out of date, so I'm going to close it in favor of #452. See the discussion there for more current TAILS status.
