### ISSUE TITLE
Is ricochet ID sensitive?

### ISSUE THREAD

**Issue by choosefreesoftware** [ricochet-im/ricochet#330]
Is the ricochet ID a sensitive identifier, meaning does it defeat the purpose of this system to plain text email a person my ricochet ID? If not, could someone explain how so.

**Comment by s-rah** [comment]
See #316 for basic overview.

**Comment by choosefreesoftware** [comment]
#316  still doesn't answer whether sharing ricochet ID is detrimental to anonymity. If I shared my ricochet ID, will an observer be able to correlate my hidden service with my real identity, or is there a design in ricochet which somehow separates the ID with the hidden service, and thus still keeps one anonymous?

**Comment by s-rah** [comment]
If you share a ricochet ID publicly, using a medium attached to you e.g. an email - then an attacker could correlate your identity with that ID, and thus the hidden service - since the ricochet ID is just the hidden service address.

However, if they have the link, it doesn't give them that much information i.e. they can do all the things in #316 (e.g. tell when you are online) - but they could not see who you were talking to or what you were talking about - this is simply put "if you publicly state you are using ricochet, then an adversary knows you are using ricochet"

If you are concerned about linking a ricochet id with your identity, then you could use a couple of indirection steps e.g. send the ricochet id using PGP encrypted email - then the attacker would not be able to collect it through passive monitoring.

**Comment by choosefreesoftware** [comment]
Thank you for the clarification!
