### ISSUE TITLE
Can't run ricochet

### ISSUE THREAD

**Issue by delaRosa12345** [ricochet-im/ricochet#347]
Hi guys,

Could you guys help me out? Newbie here. Can't run ricochet in an extracted folder from a static build 64bit - also it's the latest release. I'm running Tails 2.0.1. "bash: ./ricochet: No such file or directory", that's what it says when I try to run it. I've successfully run Ricochet from Jessie 8.3 via ./ricochet. For whatever it's worth, that was probably the previous release. 

Thanks a lot!

**Comment by special** [comment]
Ricochet isn't able to run on Tails currently, because the Tails firewall blocks Ricochet's separate instance of tor (specifically, because it blocks listening on localhost ports).

We're hoping to get a solution that will allow using Ricochet with the system copy of Tor on Tails, but there are some complications to solve first. For now, I don't have a solution for you on tails. Sorry!

#31 covers some of this problem.

**Comment by delaRosa12345** [comment]
Ah, got it! Thanks  a lot!
