### ISSUE TITLE
How are addresses so short?

### ISSUE THREAD

**Issue by lmatteis** [ricochet-im/ricochet#349]
If you look at Bitcoin addresses for example, they seem much larger than Ricochet's addresses (16 chars vs 33 of bitcoin). How do you guys achieve this compactness? Are you guys using a shorter hashing algorithm to hash public keys?

**Comment by lmatteis** [comment]
These seems to be the normal length for onion addresses. I'll ask the Tor community :)

**Comment by special** [comment]
The details you're looking for are in the tor rendezvous specification[1]

Onion addresses are the first 80 bits of the SHA1 hash of a RSA public key. In the next generation hidden services proposal[2], they will get much longer in order to fit an entire Ed25519 public key.

[1] https://gitweb.torproject.org/torspec.git/tree/rend-spec.txt
[2] https://gitweb.torproject.org/torspec.git/tree/proposals/224-rend-spec-ng.txt

**Comment by lmatteis** [comment]
Cool. You guys have any thoughts on how to make them more memorable... if that's even something you're looking into.

**Comment by s-rah** [comment]
@lmatteis I wrote some thoughts in #128 a while back - but it's a hard problem :)

**Comment by lmatteis** [comment]
@s-rah thanks! I was actually thinking of using an encoding with an alphabet which only uses unicode images - for instance emojis :) Not sure how serious it can be taken but certainly better then long streams of random chars. Your approach of using mnemonic names also is cool.
