### ISSUE TITLE
Integrated anonymous payments

### ISSUE THREAD

**Issue by mateli** [ricochet-im/ricochet#353]
The ability to right click a user and choose "send money" should be quite useful. And of course that option should be there in a chat window. 

There are a number of projects that's working on anonymous payments. Integrate one or more into the IM.

**Comment by ddfssdfkofdsfighdfuigf** [comment]
God no. Don't start giving them ideas for useless bloat and dependencies on third parties!!

**Comment by mateli** [comment]
How are the ability to send money "useless bloat". Such a feature is could of course be optional. 

Why would they add dependencies on third parties? I see multiple ways of doing this that doesn't do that.

**Comment by ddfssdfkofdsfighdfuigf** [comment]
I assumed that by "There are a number of projects that's working on anonymous payments.", you were referring to some sort of commercial service. If you mean Bitcoin, it's much better, but still pointless bloat, especially at this early stage.

**Comment by mateli** [comment]
I am referring to forks of bitcoin with improved anonymity. As those are open source they can be studied and incorporated. I think they should be optional plugins rather than part of the core application. 

It is possible that payments has impact on the design of the core messaging protocol so it should at least be discussed in this early stage.

**Comment by e-sushi** [comment]
I tend to agree with the “avoid useless bloat” mantra. Instead of adding stuff like this suggestion to the core, it would be rather something that should be implemented as “optional plugin functionality”. That way, everyone should be happy…

**Comment by burdges** [comment]
We've discussed eventually adding [Taler](https://taler.net/) payments with messaging in GNUnet.  It's a good idea in the very long term, but..

In the shorter term, I think payment systems should focus on being user friendly in a variety of contexts by intelligently exporting payments encoded as text, not just gaining special support from a few applications, and messaging applications should focus on larger security concerns. 

We're adding export and import coins functions to Taler for sharing money between friends who trust one another.  We'd probably recommend that text mediated real payments be handled using export and import with the recipient then making an actual payment.  It's suboptimal because the merchant might not give the customer their signed receipt, but that's probably okay for most chat scenarios. 

Afaik ZeroCoin is the only AltCoin with credible anonymity.  I donno if it can export transfers as text, but if not I'm sure someone will add that.  It's not like ZeroCoin has any notion of signed receipt besides the entry in their BlockChain.

**Comment by burdges** [comment]
As an aside, anonymity in Taler or ZeroCoin is far superior to the pseudononymity in BitCoin, but it's only one-sided in the sense that only the customer gains anonymity.  It's therefore a deanonymization vector for the merchant side in context of a private messaging system.

**Comment by ddfssdfkofdsfighdfuigf** [comment]
"Unlike BitCoin or cash payments, Taler ensures that governments can easily track their citizen's income and thus collect sales, value-added or income taxes."

In other words, Taler is absolute rubbish.

**Comment by mateli** [comment]
I'd use pidgin as an example of a successful plugin-based platform. However it's code is fairly bloated and complex leading to it's current stagnation. 

I think zerocoin is the best candidate I've seen so far. However another approach would be to rethink the transaction model based on the fact that ricochet plugins has an IM protocol available.  Messages back and forth could be part of the transaction. 

For example a new zerocoin wallet could be created for each transaction. You would use the ricochet identity to specify recipient of a payment, then the IM would exchange wallet data as messages. Once the payment come through to the temporary wallet you they would be transferred to the real wallet and the temporary one would be dropped. 

Another more simple solution would be to have a client-server approach where a database manages transactions. This would be like having a bank and the bank/server would just be a service running ricochet. This has the disadvantage that it's not a universal system where all ricochet can send money to all other users. One would be limited to sending money within a bank. Also someone would have to run the bank. From a programming perspective this is the easiest solution. That's the only reason I bring it up, as I would very much prefer a global system.

**Comment by mateli** [comment]
Well actually the bank-like approach does have some advantages that I didn't immediately thought of. The ability to set up community banks with it's own money creation may make it possible to ger fully functional economies where there is a lack of pre-existing money.

**Comment by special** [comment]
This is pretty far outside of Ricochet's scope. I don't see it happening any time in the foreseeable future - this should all be a separate project.
