### ISSUE TITLE
ricochet won't start under Windows 10

### ISSUE THREAD

**Issue by ksjs** [ricochet-im/ricochet#442]
I have recebtly upgraded to Windows 10 pro, version 1511, build 10586.494. After downloading ricocet's latest portable version, I realised that it won't start. Does there exist a workaround?

**Comment by special** [comment]
My first guess on issues like this is OpenGL. Those problems should be fixed by #367 in the upcoming 1.1.4 release. It also contains other fixes and updates that may help.

Since there's not more information here, I'll close this in favor of #367. Please get in touch if problems continue after 1.1.4, so we can try to dig out more information.
