### ISSUE TITLE
Ricochet wont start in Win 8.1

### ISSUE THREAD

**Issue by mariasmith71** [ricochet-im/ricochet#445]
Re-installed the app two times, and for 3 times it does not launch/start. Help anyone?
thanks /maria

**Comment by migueldemoura** [comment]
Do you get any error message?

**Comment by special** [comment]
My first guess on issues like this is OpenGL. Those problems should be fixed by #367 in the upcoming 1.1.4 release. It also contains other fixes and updates that may help.

Since there's not more information here, I'll close this in favor of #367. Please get in touch if problems continue after 1.1.4, so we can try to dig out more information.
