### ISSUE TITLE
Won't start on Windows 7 64bit

### ISSUE THREAD

**Issue by TopNumbers** [ricochet-im/ricochet#447]
No error, Ricochet simply won't open!

**Comment by special** [comment]
My first guess on issues like this is OpenGL. Those problems should be fixed by #367 in the upcoming 1.1.4 release. It also contains other fixes and updates that may help.

Since there's not more information here, I'll close this in favor of #367. Please get in touch if problems continue after 1.1.4, so we can try to dig out more information.
