### ISSUE TITLE
Ricochet ID is the same on different computers on the same network

### ISSUE THREAD

**Issue by AlexanderKayumov** [ricochet-im/ricochet#449]
I tried to use Ricochet for communicating with my wife, who is on another computer on the same network. However, I was rather surprised when I saw that Ricochet had assigned us both THE SAME Ricochet ID, making it impossible for us to communicate.

I think it's a pretty weird issue. It's like if colleagues on the same network couldn't send emails to each other, or if texting stopped working for people in the same building...

**Comment by burdges** [comment]
Ricochet itself knows nothing about your local network.  You've copied your ricochet id from your computer to your wife's computer.  You maybe did this when copying the binary because ricochet sometimes places it's config directory with the ricochet binary, which seems off for a unix program.  Just delete the ricochet config directory from your wife's computer and it'll make a new one.

**Comment by AlexanderKayumov** [comment]
Ok, gonna try that! Thank you!

**Comment by AlexanderKayumov** [comment]
Thanks! It worked! :)

**Comment by burdges** [comment]
I'm worried now.  I've only built ricochet from source, and only on Linux, so I'm not familiar with this setup file.  

If someone gave you a setup file with preset key material, then they could sniff your ricochet communications.  If you're at all worried then you could make a new ricochet account for yourself in the same way.  If you back up the file 'config/ricochet.json' first, then you can readd your contacts from it.

**Comment by AlexanderKayumov** [comment]
Well, maybe I misremember something...

I've downloaded Ricochet again and now everything is fine. I've now gotten a new Ricochet ID for myself.

Thank you so much for your help!
