### ISSUE TITLE
Let user to use Tor hosted on other PC.

### ISSUE THREAD

**Issue by GitHubHatesTor** [ricochet-im/ricochet#463]
a. I don't want to use tor.exe which bundled with ricochet.
b. I don't trust 3rd party tor.exe
c. I want to let Ricochet to use TBB's tor.exe.
etc.

Allow user to configure Ricochet to use other Tor proxy, and also allow incoming ports.

[X] Use Tor on Network (Advanced)
Tor IP:Port [ 10.10.20.30:9050 ]
ListenIP:Port [ 10.10.20.20:4156 ]
My Onion: [ xxxxxxxxxxxxx ].onion

RICOCHETPC(.20) ----9050----> TORNODE(.30) (to connect to tor network)
RICOCHETPC(.20) <---4156----- TORNODE(.30) (configure TORNODE's torrc, set up hidden service and route traffic)

**Comment by special** [comment]
There are not currently settings in the UI for this, but:

> a. I don't want to use tor.exe which bundled with ricochet.
> b. I don't trust 3rd party tor.exe
> c. I want to let Ricochet to use TBB's tor.exe.

You can replace the tor.exe included with Ricochet with any recent version of Tor, including the tor.exe from Tor Browser. Ricochet's tor build is not modified in any way. If you remove the tor.exe file included with Ricochet, it will attempt to use tor.exe from your system's %PATH% instead.

> Allow user to configure Ricochet to use other Tor proxy, and also allow incoming ports.

Ricochet requires access to the Tor control port to monitor connectivity and publish services. I believe Tor Browser does not expose the password for its control port by default.

However, both Tor Browser and Ricochet observe the `TOR_CONTROL_HOST`, `TOR_CONTROL_PORT`, and `TOR_CONTROL_PASSWD` environment variables. If these are set, Ricochet will attempt to connect to that control port instead of launching its own instance of Tor.

**Comment by fate14** [comment]
Wait, we can $(cp /usr/sbin/tor ~/ricochet/) ? This will overwrite the bundled (and older) tor binary with the torprojects version of tor, v0.2.8.9? This is safe to do? There seems to be a bit of debate:

https://tor.stackexchange.com/questions/12596/ricochet-tor-version-is-out-of-date

**Comment by special** [comment]
@fate14 yes, it is safe to replace. Ricochet ships with an unmodified tor binary and does not require any particular build configuration for tor. Any 0.2.7 or 0.2.8 version should work fine. I believe there are bugs with hidden services in the current 0.2.9 alpha versions that may impact reliability.

If you have a tor in your system PATH, such as one installed by a package manager, you can go a step further and just remove ricochet's `tor`. It will use the one in PATH directly instead.

**Comment by GitHubHatesTor** [comment]
> Ricochet requires access to the Tor control port to monitor connectivity and publish services.

I do not want to expose Tor's "control" port(example's .30) to the network, this is a security risk.
I run several Hidden Services and I know how to operate these.
I want Ricochet to use my "Tor socks5 proxy".

---
[X] Use Tor on Network (Advanced)
Tor IP:Port [ 10.10.20.30:9050 ]
ListenIP:Port [ 10.10.20.20:4156 ]
My Onion: [ xxxxxxxxxxxxx ].onion
---

If I can configure this in Ricochet, you don't have to include outdated Tor.
(Also, please consider moving Ricochet's tor & tor DLLs to other folder, such as "Ricochet/tor/"
so the user can easily replace them)

**Comment by GitHubHatesTor** [comment]
> If you have a tor in your system PATH, such as one installed by a package manager, you can go a step further and just remove ricochet's tor. It will use the one in PATH directly instead.

Talking about Linux, I presume.
If the user is using Windows and he/she installs Tor or TBB to ! %windir% folder, Ricochet can't find tor.exe.

**Comment by GitHubHatesTor** [comment]
Related: https://github.com/ricochet-im/ricochet/issues/452

If only Ricochet NOT use ControlPort(allow Listen-server mode)...

**Comment by special** [comment]
Ricochet uses the control port to monitor tor's circuit state as well as publishing services. This is important in order to get better behavior for attempting connections to contacts, and will become even more important in the future. There are no plans to make the control port optional.

Aside from that, manually configuring services is not acceptable for most users (e.g. on TAILS). Also, because both Ricochet and Tor require access to the service's private key, there is a lot of potential for misconfiguration that would lead to a broken client.

If you're concerned about the security of exposing a control port, some distributions have adopted control port filters to restrict the available commands. See for example https://github.com/subgraph/roflcoptor and https://github.com/Yawning/or-ctl-filter

> If the user is using Windows and he/she installs Tor or TBB to ! %windir% folder, Ricochet can't find tor.exe.

The tor.exe file itself needs to be in one of the paths under %path%. It cannot be in a subdirectory.
