### ISSUE TITLE
Add support for MathJax

### ISSUE THREAD

**Issue by e5f3c2ea895af0f27667** [ricochet-im/ricochet#509]
It's unfortunate that there is no way to communicate mathematical formulas using Ricochet. It would be great if there was some support for MathJax.

**Comment by afk11** [comment]
Sounds neat and all, but I'm not sure what place javascript libraries/engines have in ricochet.

**Comment by special** [comment]
Ricochet supports unicode, so all unicode mathematical symbols are available. For example, something like `∀(x, y ∈ A ∪ B; x ≠ y) x² − y² ≥ 0` (taken from [this tool](http://math.typeit.org/)) will display fine (as long as you have a font for it).

Unfortunately, that's as much as we can do. Systems like MathJax are large and complicated and present too much of an attack surface for little benefit. Actually, Tor Browser disables parts of Firefox's mathematical equation support at higher security levels because of previous vulnerabilities.

**Comment by e5f3c2ea895af0f27667** [comment]
@afk11  @special Thanks for the comments. Can't it be added as some sort of plugin? I didn't say that it should be supported and enabled by default just that it would be great to have a way to render maths using MathJax locally.

**Comment by special** [comment]
There isn't any kind of formal plugin system, and there aren't plans to add one -- complexity and risk. The focus in mainline Ricochet is on getting the simple things _right_, and there just isn't enough time and energy to do everything.

That said, it's absolutely possible to modify and rebuild your Ricochet to be able to render mathematical formulas. It's unlikely that we'd merge it into the "mainline" here, but it sounds like having that patch might make at least your life a little better. That's as much as I can offer for now :/
