### ISSUE TITLE
Duplicate messages in rare scenarios

### ISSUE THREAD

**Issue by rburchell** [ricochet-im/ricochet#515]
We saw an instance of duplicate messages the other day.

Hypothetical scenario explaining that is this:

* Bob sends message ABC
* Alice receives them, sends acks to Bob
* Bob (or Alice) has connectivity disruption, and does not recieve the ack
* Bob and Alice reconnect
* Bob (automatically) sends message ABC again (since he never got the ack of the original send; believing it to be undelivered)

**Comment by rburchell** [comment]
Possible solution: tag each message with a UUID, check for duplicates when adding.

**Comment by special** [comment]
Messages do have an ID now, but they are probabilistically unique, not universally, between connections. I think it'd be a good idea to transition to a UUID also, but this can be solved with something like:

When receiving a message:

1. If message ID is zero, do nothing
2. Scan message history in reverse chronological order, stopping at the first _acknowledged outbound_ message (the first point we are certain the peer has), or some arbitrary very small limit
3. If any message in the scan is exactly equal by message ID and message text, drop the new message but send an acknowledgement for it
4. Otherwise, proceed normally

**Comment by wfr** [comment]
An easy way to test it: https://gist.github.com/wfr/e174692fda79703177e2abcde5056bc7

**Comment by rburchell** [comment]
@special Yeah, I mentioned UUIDs just because I think it makes the process easier. I agree that it isn't immediately necessary.

@wfr Nice work! Thanks :)

**Comment by special** [comment]
\o/
