### ISSUE TITLE
Update Tor to 0.2.9.10

### ISSUE THREAD

**Issue by Rspigler** [ricochet-im/ricochet#538]
Ricochet is currently running version 0.2.8.9 of Tor, while version 0.2.9.10 was released on March 1st, 2017, and the 0.3.0 series is almost stable.

This is an updated issue of https://github.com/ricochet-im/ricochet/issues/487 which requested an update to Tor version 0.2.8.12

Ghost (user now deleted) suggested un-bundling Tor from Ricochet, which would allow users to ensure they are always running an up to date version, for example just by simply keeping TBB up to date on their system (https://github.com/ricochet-im/ricochet/issues/487#issuecomment-268219484).  This would also reduce the developer's workload in order to focus on larger enhancements that have been in the works (for example, file transfers).

@migueldemoura brought up the issue of keeping the application as noob friendly as possible, and in response suggested having two download options - One with tor bundled in order to keep the installation process as simple as possible, and one without tor for the reasons described above (https://github.com/ricochet-im/ricochet/issues/487#issuecomment-271102716).

I have no coding experience and am just a lurker in most online communities, but I believe Ricochet to be the most secure and necessary messaging application that finally fixes the metadata problem.  Because I have no rep, I should not be one of the signatories, but I would be more than glad to contribute $50 worth of bitcoin to a multisignature address controlled by trusted individuals in this community in order to implement the above updates and incentivize more consistent development work for this badly needed tool.  With Whonix 14 hopefully being released soon with Ricochet implemented, this will be able to reach an even larger user base.

@special Please let me know your thoughts on this, and I'd love comments/suggestions from the rest of the community on who they believe the signatories should be, and what others would be willing to contribute, either in donations or in code.

**Comment by rburchell** [comment]
I've repurposed #487 to track the need for the update, as it has a little more "hard" information, I don't think there's a need to duplicate it again here. Thanks for the bump, though.

Thanks for your offer of funding, let's use the Salt issue to discuss that sort of thing further.

**Comment by fhj39** [comment]
**> Ghost suggested un-bundling Tor from Ricochet...**

I agree, there might be some justification for this:

**1.  COMPATIBILITY**

> migueldemoura brought up the issue of keeping the application as noob friendly as possible

I had to abort the installation on Windows because it appeared that Ricochet wants to over-write a newer version of Tor with its bundled (older) version from Ricochet 1.1.4 (November 5, 2016).  I already have Tor Browser and Tallow installed, so I am not sure what is going to be replaced and the justification for doing so.


**2.  TRANSPORT AGNOSTIC**

both I2P and Tor have some open issues with their use of Distributed Hashtable (DHT) technology prone to sybil attacks. GNUnet has designed its routing (core) and GNU Name System (GNS) in ways that are resistant to such attacks.

http://secushare.org/anonymity
