### ISSUE TITLE
[NEWS] The Tor Project said this software is a "Discontinued software".

### ISSUE THREAD

**Issue by ghost** [ricochet-im/ricochet#579]
https://trac.torproject.org/projects/tor/wiki/doc/TorifyHOWTO/InstantMessaging

Copy start:

---

Software listed here has become depreciated and development has ceased. They are therefore considered unsafe and it is highly recommended to avoid using them. This section is here purely for historical value. 

Ricochet IM is an open-source, decentralised instant messenger project that officially ended development in November 2016. Ricochet starts a Tor onion service on the users local system and facilitates communication with other Ricochet users whom are also running their own Ricochet-created Tor onion service, providing End-to-End encryption by never allowing the connection to leave the Tor network. 

---

Copy End. What's the alternative? "qTox over Tor"?

**Comment by ilovelinux** [comment]
As @s-rah said, devs are writing libraries to make Ricochet more usable https://github.com/ricochet-im/ricochet/issues/555#issuecomment-324094653
Ricochet is secure. I think there are no doubt on this. If you still have some let's read how Ricochet works: https://ricochet.im/#how-it-works, https://github.com/ricochet-im/ricochet#how-it-works, 
>Copy End. What's the alternative? "qTox over Tor"?

qTox works in a little different way, it's not built on the Tor Network (so it exposes your IP) and it uses its nodes to bootstrap. I prefer Ricochet to qTox because of it.
Anyway qTox is only one of the many toxcore clients. It's better talking of toxcore vs Ricochet

**Comment by tox-user** [comment]
>Copy End. What's the alternative? "qTox over Tor"?

Yes, you can use Tox over Tor.

**Comment by ghost** [comment]
@ilovelinux
## Software listed here has become depreciated and development has ceased.
## They are therefore considered unsafe and it is highly recommended to avoid using them. This section is here purely for historical value.

**Comment by ohmynameisrico** [comment]
@ilovelinux
If you are blind enough to trust Tor statement, create a ticket in trac.tpo.

**Comment by ghost** [comment]
@ilovelinux
"Ricochet is secure" is completetely BS. At least 10+ vulns are found and you still say secure?
Source is already open, find it yourself. And stop yelling secure which is a FUD.

**Comment by ilovelinux** [comment]
Can you link something about these 10+ vulns?
